### ISSUE TITLE
Textual issues documentation / readme.md / wiki

### ISSUE THREAD

**Issue by Gerbrand-V** [tudelft3d/3dfier#105]
++ ISSUES REGARDING DOCUMENTATION ++
General
* A hint with respect to system requirements to run the software would be nice. At present a 64bit operating system is implied and for Ubuntu a specific version is mentioned. Are there, however, any actual hardware requirements (Min. mem, cpu, gpu, required disk space etc).
* The installation instructions can be found in at least two or three locations (documentation/readme.md/wiki, at least for Windows). Centralizing seems logical and might alleviate apparent discrepancies
* The PDF in the repository isn't as up to date as the documentation in GIT. Is the PDF required, or would a redirection to the online documentation suffice?
* The word "developped" has already been corrected to "developed". Although the readme is correct, the 3dfier documentation (webpage) still shows the incorrect word. Does the page need to be generated again?
* Installation on windows suggests using precompiled binaries a lot. Can all the dependencies also be built from source (or using something like vcpkg or a nuget-package)?

***** DOCUMENTATION *****
==== GETTING STARTED ====
:::: FIRST RUN ::::

... Verify installation...
commandline options are mentioned here, but not explained. Could a link to the (or the actual) explanation be added here?

:::: INSTALLATION ::::

--- WINDOWS ---
1...Running installers...
1. The link to VS2017 points to VS2019
2. CMake. No version is stated. Am I given to understand that any/the most recent version of CMake would work?
3. Boost precompiled. Here a version is mentioned. Would the software also work with an older (or newer) version of Boost? If any version (after a certain date) is ok, than a reference (Boost version >= n.nn) would be nice. As it is now, it looks as though a very specific version is required (Note: the Windows 10 Wiki mentions another versions). Furthermore: the suggested version for Boost ends on 14.0. This designates the VS2015 Toolchain, not the VS2017 toolchain as suggested further on. Since the VS2017 compiler was mentioned specifically, displaying the 14.1 version file might be less confusing. Furthermore this Boost installer explodes to approx 2 Gb. Is it really necessary to install all Boost libraries or is a selection sufficient (see also next point).
4. OSGeo4W: GDal is quite extensive. Parts of GDal require Boost and will only install if Boost is also installed at the same time (it does not recognize the previously installed Boost version). Is this version of boost sufficient and  could the Boost precompiled binaries be skipped? 

2...Dependencies...
Yaml-cpp is currently at version 0.6.3 and not  0.5.3. Is the 0.5.3-version strictly necessary or would any version do (for instance the latest version)

INSTALLATION:
3. Set environment variables
"Go to Control Panel > System > Advanced system settings > Environment Variables and add the following user variables. Note that the version numbers may be different!"
Not only the version might be different, but also the paths in which the libraries are installed.

==== EXAMPLES ====
:::: Large scale topography (BGT) to 3D ::::
Page is empty.

:::: Simplification of terrain ::::
There are three headers, but no further text. A pointer/referral to the lifting-options might be practical here, but a separate (short, self contained) explanation might also be practical (no idea what the intention of this part was). 

The documentation in the repository (PDF) is older (10 March 2019) but has the same version number as the documentation in Git itself (1.2.2). If you pull the repo, the PDF will not be the latest version, which might become confusing. Is it not more practical to leave ou the PDF and for documentation point to the documentation section in Git? Otherwise a statement to that effect somewhere in the PDF might help.

==== Architecture ====
--- Data flow through the program ---
This section is filled with only a diagram, the rest of the headers do not contain any information (Configuration, Data integrity check, Handling polygons, Handling points, Magic, Creating data). Specifically the 'Magic' section speaks to the imagination :-)

GITHUB
Under the header "Documentation" it states that the documentation will instruct on "how the 3dfier algorithm works". This is not the case. The question is, whether this is necessary or that a separate algorithm description would suffice or that one should just look at the code (if that is well enough documented)?

Again there are installation instructions. Please make 1 place where these instructions can be found, as multiple places are confusing and tell slightly different things.

Github:
In the Readme.md in the repository a number of references are made to precompiled boost-binary/Yaml/OSGeo4W/CGAL. Here no explicit version numbers are mentioned. This differs from other places where these libs were mentioned. 

Wiki Windows 10: Yet another version of Boost/CGAL is mentioned here. As stated above leaving out numbers or providing a 'minimum'-version number would be more practical. Furthermore liblas/laszip is installed from OSGeo4W contrary to what the documentation states (there they must be installed separately). Which parts of OSGeo4W are required (list?). Could, for instance, GDal also be installed separate from OSGeo4W? Would installing QGis suffice to meet most of the demands here (CGAL/GDal/?)?

The download for the VS2017 solution/proj files comes from a dropbox. Is it possible to put these in the repository as well (separate folder) or to create them with CMake (or something like that)?

**Comment by tcommandeur** [comment]
Thanks for the comments and the review. 

The idea of the documentation/readme.md/pdf is that the documentation is going to be the only source. The Readme will link to the doc's and the PDF will be removed soon.

Providing versions of the dependencies or a range of supported versions is a bit of a thing. In theory all versions above a certain version should work however not all libraries keep backwards compatibility. It's impossible to test all combinations of dependencies and their versions. There should however be a good explanation that the supplied versions are tested and that newer versions should work too. For all different versions that problem should be solved when there is only one source for documentation.

Documentation for the examples and architecture are in progress. 

All other points will be taken into account in the next draft.

P.S. Today the latest changes for the architecture will be online with the most current information. Commits are done in the github-pages branch where a merge to master is necessary for the website to update.
