### ISSUE TITLE
Expression expansion goes wrong in VS2017

### ISSUE THREAD

**Issue by Gerbrand-V** [tudelft3d/3dfier#108]
VS2017 tries to expand the std::min and std::max operators and finds it cannot do that for certain lines in Map3D.cpp (cf image)

![image](https://user-images.githubusercontent.com/42830745/73938518-b801ea80-48e7-11ea-9123-c58783e0e75c.png)

Is this VS2017 specific, are some additional intermediate structs in order or do I need some extra brackets somewhere?

Or is the min operator overloaded somewhere (by one of the dependencies) and is the order in which I build the software (or the order in which I include things) an issue?

**Comment by tcommandeur** [comment]
Never seen this issue before, could it be you are accidentally including windows.h/windef.h header files?

https://stackoverflow.com/questions/5004858/why-is-stdmin-failing-when-windows-h-is-included

**Comment by Gerbrand-V** [comment]
Thank you for the suggestion. windows.h nor windef.h were include, but I added
#undef min
#undef max
just below the include in Map3d.cpp and now the error message has disappeared.
