### ISSUE TITLE
Compiling Laslib

### ISSUE THREAD

**Issue by Gerbrand-V** [tudelft3d/3dfier#110]
In the documentation two options are provided to compile Laslib in order to use it for 3dfier. The first option (autoconvert the VC6 .dsp-file to VS2017) introduces a lot of additional effort, since several dependencies of VC6 are not converted correctly. The second option (use CMake) works fine:

In the LASTOOLS folder
mkdir build
cd build
CMake -A x64 ..\ 

Creates a correct solution-file for VS2017. Is it maybe practical to leave option 1 out of the documentation?

**Comment by tcommandeur** [comment]
Changed in documentation by removing option 1.
