### ISSUE TITLE
Docker build does not work from WIndows

### ISSUE THREAD

**Issue by Gerbrand-V** [tudelft3d/3dfier#113]
I've tested the docker version of 3dfier and am stuck. There are several issues with the documentation as well as the actual build:

- Documentation is unclear, specifically with respect to where the folder-structure has to be made and where the shell-script should be located for everything to work

- For windows systems: add that the line-endings should be LF not CR/LF as is the standard on Windows

- The shellscript does not work. I get the message "no targets specified and no makefile found
" if I run it (either from within the image in bash or from the commandline

- Would it not be easier to create an image within which 3dfier is built, rather than building it in such a way that the build-output is written to the host-system?

- The cuild_3dfier.sh script could be added to the git repo or added to the docker image; there seems to be no reason why a user is required to make this file and has to mount it in a container

- "$(pwd)" is not understood by Windows (neither powershell, nor CMD)

**Comment by balazsdukai** [comment]
The Dockerfile and method on the `master` branch is outdated and essentially just a hack, and I agree with each of your points. There is an updated docker image on the `development` branch and I also updated the instructions in the documentation.

The updated image conforms to what you describe and a new image is built from the master, development branches and each release and pushed to https://hub.docker.com/repository/docker/tudelft3d/3dfier
