### ISSUE TITLE
Version 1.3 doesn't run my "old version 1.2.2" YAML file

### ISSUE THREAD

**Issue by HarmenK** [tudelft3d/3dfier#121]
I am trying to run a YAML file that gave output with the 3dfier 1.2.2 version. 

At the moment 3dfier 1.3 found the file valid but doesn't run, so no output...
Find the yml file attached

[ISSUE_3dfier_v13.zip](https://github.com/tudelft3d/3dfier/files/5582458/ISSUE_3dfier_v13.zip)

**Comment by hugoledoux** [comment]
I improved the handling of paths and added relative paths, and thought this was tested. 

What is the error you get?

**Comment by HarmenK** [comment]
Actually... no errors
It just doesn't do anything: it's reading the yml file, reporting the locations of the geopackages and then quits...

![image](https://user-images.githubusercontent.com/35258842/99985497-50e9ef80-2dae-11eb-8f7a-ee35ae5cd8a2.png)

**Comment by hugoledoux** [comment]
I tried to replicate your error under Windows but I cannot. Are you 100% sure that there's a file at that location?

Maybe you can try to see if you can run the `testarea_config.yml` in `/example_data`?

**Comment by HarmenK** [comment]
Well, the testdata works...
So, very weird that my 'old' data seems to go wrong in the new version of 3dfier.
Rewriting the yml didn't give any solutions
Also all data is still in the same directories.

I'll give it a try to start from scratch with building the data and the yml file.

**Comment by hugoledoux** [comment]
I know why: you used wildcards (*) and my update of the paths didn't consider them.

I have a fix in branch "glob": could you try it with different versions please? Once working I'll merge to master.

**Comment by HarmenK** [comment]
Yes, I will
Thanks Hugo.
As soons as I have results, I'll let you know

**Comment by HarmenK** [comment]
@hugoledoux : how do I implement the fix ? I don't have experience with that :-)

**Comment by HarmenK** [comment]
> @hugoledoux : how do I implement the fix ? I don't have experience with that :-)

**Comment by HarmenK** [comment]
@hugoledoux : not closed for now, actually... Can you still help me with implementing the fix? Do I need to build a file?

**Comment by hugoledoux** [comment]
hmmm, okay I has assumed that since Future Insight's www.nederlandin3d.nl is built with 3dfier that you guys could compile C++ code.

So what you need to do is build the binary/exe from the source code, it's explained in the doc for Windows: https://tudelft3d.github.io/3dfier/installation.html#windows

You need to build for the branch mentioned above, not master

**Comment by HarmenK** [comment]
Ah, ok. No I'm sorry I'm not building the files.

So, ignoring this issue with the path, another issue pops up: buildings should be LoD0, but they are floeating above the surface and are extremely extruded.

For now, in my current project, I'm back to 1.2.2
