### ISSUE TITLE
osm data with 3dfier

### ISSUE THREAD

**Issue by adam314315** [tudelft3d/3dfier#137]
Hello,

Could you please explain how to use osm data shapefile once exported and use it as an input for 3dfier ? As far as I understand 3dfier would need to combine the shp file with an elevation dataset in Lidar format but couldn't find any data. Any help would be appreciate. Thanks.

**Comment by hugoledoux** [comment]
see this: https://tudelft3d.github.io/3dfier/generate_lod1.html

If you use data in Netherlands then https://downloads.pdok.nl/ahn3-downloadpage/ can be used as elevation, if outside then you need to find yourself a source of elevation data.
