### ISSUE TITLE
Generation of terrain from LAS

### ISSUE THREAD

**Issue by fbiljecki** [tudelft3d/3dfier#14]
Enable generating the TIN around the input building polygons

**Comment by tcommandeur** [comment]
@fbiljecki can you give an example? If only building class is supplied then use all points in between to generate a TIN?

**Comment by fbiljecki** [comment]
Yes, that is what I mean exactly. For example, if only building footprints are available from OpenStreetMap.

**Comment by tcommandeur** [comment]
If a polygon is generated for the extent and the building polygons are removed from it this can be configured as terrain. This will result in a tin around the buildings.

**Comment by fbiljecki** [comment]
Sure, then we can make a note about that in the readme, or even a short tutorial on how to do that.

**Comment by tcommandeur** [comment]
A wiki has been created on this issue [wiki/Generation-of-terrain](https://github.com/tudelft3d/3dfier/wiki/Generation-of-terrain)
