### ISSUE TITLE
Fix vertex height set to -9999

### ISSUE THREAD

**Issue by tcommandeur** [tudelft3d/3dfier#18]
When applying simplification in terrain or forest classes some boundary vertices are set to -9999 even though there are ground points within radius.

Without simplification:
![less_wrong_heights](https://cloud.githubusercontent.com/assets/19147421/19484088/acf20c08-9556-11e6-8c2b-049d23d703e9.png)

With simplification:
![wrong_heights](https://cloud.githubusercontent.com/assets/19147421/19484089/acf351e4-9556-11e6-9fe2-45abbdc20cfa.png)

**Comment by hugoledoux** [comment]
I wrote function to put them at the average height of the vertices in a polygon. And it works, except when there are no lidar points at all in a whole polygon, and for that I put back "0".

Putting -9999 means that you create VW to these very low (and unrealistic) ones. We could do that, but then the stitching needs to consider these explicitly. I am not sure it's worth it, but not sure what was the problem of Kadaster with the elevation that are not covered by lidar?

**Comment by tcommandeur** [comment]
This is partly solved by the averaging of Hugo, not going to do anything else here. Input point cloud should be covering the features enough.
