### ISSUE TITLE
Question about building 3dfier on Windows 10 and with Visual Studio Community 2015

### ISSUE THREAD

**Issue by GreenUtil** [tudelft3d/3dfier#19]
Hi, I am trying to build the 3dfier with CMAKE. On Windows 10 and with Visual Studio Community 2015. When building in Visual Studio I get an error message related to Boost. Boost is one of the components I don't have much experience with, so perhaps anyone can give a clue ? 

Error	LNK1104	cannot open file 'boost_thread-vc140-mt-1_62.lib	

Greetings,

Barent Brouwers

http://www.3dgeosolutions.nl/

Hoi, ik probeer de 3dfier te bouwen met CMAKE. Op Windows 10 en met Visual Studio Community 2015.  Daarbij krijg ik een foutmelding die met Boost te maken heeft. Het project 3dfier heeft voor mij sowieso een aantal nog onbekende componenten. Visual Studio geeft de volgende melding:  
Error	LNK1104	cannot open file 'boost_thread-vc140-mt-1_62.lib

**Comment by tcommandeur** [comment]
Hi Barent,

The Boost library is a library which is used for the geometric intersections. There are several ways to solve this;
1. Add the NuGet package with the prebuild binaries; https://www.nuget.org/packages/boost-vc140
2. Downlaod the prebuild binaries and set the path in the project → C++ → General → Additional Include Directories; https://sourceforge.net/projects/boost/files/boost-binaries/1.62.0/boost_1_62_0-msvc-14.0-64.exe/download

If the path for the libraries is resolved correctly the build error will disappear.

**Comment by hugoledoux** [comment]
why are you using CMake actually? There is a Visual Studio project file included.

I know it doesn't solve the Boost, but could simplify your life.

**Comment by GreenUtil** [comment]
Well thanks, I overlooked the vs_build folder.....
But when I load the 3dfier.sln I am getting an error, because 

<ProjectReference Include="..\..\yaml-cpp\vs_build\yaml-cpp.vcxproj">

can't be found....

I am going to try now the above mentioned solution for Boost with NuGet. 
Here at 3DGeoSolutions we already had some more problems with CMAKE and Visual Studio. Going back from VisualStudio version 2015 to 2013 has solved these problems in any case.....

**Comment by tcommandeur** [comment]
Thank you for the remark, I will see to it the yaml-cpp vs-project file will also be published in the vs_build folder of this project. Also we will work on a Readme for compiling under Windows using Visual Studio.

**Comment by GreenUtil** [comment]
The Nuget route gives this error in Visual Studio 2015 : 

PM> Install-Package boost-vc140 
Attempting to gather dependency information for package 'boost-vc140.1.62.0' with respect to project 'ALL_BUILD', targeting 'native,Version=v0.0'
Attempting to resolve dependencies for package 'boost-vc140.1.62.0' with DependencyBehavior 'Lowest'
Install-Package : Unable to find a version of 'boost_coroutine-vc140' that is compatible with 'boost-vc140 1.62.0 constraint: boost_coroutine-vc140 (= 1.62.0)'.
At line:1 char:1

**Comment by GreenUtil** [comment]
The next is working fine in Visual Studio 2015, however the error Error LNK1104 cannot open file 'boost_thread-vc140-mt-1_62.lib  still remains.....

PM> Install-Package boost_thread-vc140 
Attempting to gather dependency information for package 'boost_thread-vc140.1.62.0' with respect to project 'ALL_BUILD', targeting 'native,Version=v0.0'
Attempting to resolve dependencies for package 'boost_thread-vc140.1.62.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'boost_thread-vc140.1.62.0'
Resolved actions to install package 'boost_thread-vc140.1.62.0'
  GET https://api.nuget.org/packages/boost.1.62.0.nupkg
  OK https://api.nuget.org/packages/boost.1.62.0.nupkg 29ms
Installing boost 1.62.0.
Adding package 'boost.1.62.0' to folder 'D:\Data\Barent\GloBLD\3dfier\3dfier-master\3dfier-master\build\packages'
Added package 'boost.1.62.0' to folder 'D:\Data\Barent\GloBLD\3dfier\3dfier-master\3dfier-master\build\packages'
Added package 'boost.1.62.0' to 'packages.config'
Successfully installed 'boost 1.62.0' to ALL_BUILD
  GET https://api.nuget.org/packages/boost_thread-vc140.1.62.0.nupkg
  OK https://api.nuget.org/packages/boost_thread-vc140.1.62.0.nupkg 245ms
Installing boost_thread-vc140 1.62.0.
Adding package 'boost_thread-vc140.1.62.0' to folder 'D:\Data\Barent\GloBLD\3dfier\3dfier-master\3dfier-master\build\packages'
Added package 'boost_thread-vc140.1.62.0' to folder 'D:\Data\Barent\GloBLD\3dfier\3dfier-master\3dfier-master\build\packages'
Added package 'boost_thread-vc140.1.62.0' to 'packages.config'
Successfully installed 'boost_thread-vc140 1.62.0' to ALL_BUILD

**Comment by GreenUtil** [comment]
I fixed the problem by adding the library to the Linker Additional Library Directories.
Next step is building 3dfier as a 32-bit application. (building as 64-bit gives many, many errors)
Now some other problems arise in Visual Studio Community 2015 : 

Error	C3861	'_BitScanForward64': identifier not found	3dfier	D:\Program Files\CGAL49\include\CGAL\Mpzf.h	202	

Error	C3861	'_BitScanReverse64': identifier not found	3dfier	D:\Program Files\CGAL49\include\CGAL\Mpzf.h	214
