### ISSUE TITLE
Generating geometric attributes in CityGML

### ISSUE THREAD

**Issue by fbiljecki** [tudelft3d/3dfier#23]
CityGML foresees various attributes that can be computed from the geometry, and that are available in some open datasets (e.g. Rotterdam, Den Haag). It would be nice to have them generated by 3dfier, since it anyway computes the same stuff to generate the 3D model. For example, <bldg:measuredHeight>.
Additional ideas for the attributes:
- absolute elevation of the top surface of the building and other features
- absolute elevation of the bottom (terrain height)
These two are available in the CSV output, so it would be great to have them stored in CityGML too.

**Comment by tcommandeur** [comment]
<gen:measureAttribute name="min height surface"> and <bldg:measuredHeight uom="#m"> has been available for a while. The min height is the base (floor) height calculated and the measured height is the roof height. However according to http://en.wiki.quality.sig3d.org/index.php/Modeling_Guide_for_3D_Objects_-_Part_2:_Modeling_of_Buildings_(LoD1,_LoD2,_LoD3)#Heights the measured height should be: _"The measured or computed difference between the lowest terrain intersection point and the highest roof point"._
What should be used?

**Comment by fbiljecki** [comment]
The <bldg:measuredHeight> is not defined nor elaborated by the standard. It is only interpreted by the SIG 3D modelling guide as such (though it's a reasonable explanation which I would personally follow).
However, in the context of 3dfier -- there is no percentile equivalent for that, and it's not possible to get the ridge height. Perhaps for the time being we can just use the calculated height for the top of the LOD1 (i.e. same percentile that is used in the yml)? Afaik, at the moment 3dfier cannot get multiple percentile rooftop values simultaneously, so choosing another value would make it complicated.

**Comment by tcommandeur** [comment]
As implemented in February the roof height is stored in measuredHeight
