### ISSUE TITLE
Slow performance due to invalid polygons

### ISSUE THREAD

**Issue by tcommandeur** [tudelft3d/3dfier#25]
When generating Amsterdam and a version of Zwolle the processing time increased exponentially, possibly due to invalid geometries. The invalid geometries can come from clipping/faulty conversion. In the case of the Amsterdam data ogr2ogr showed self-intersections in polygons.

Can we check and flag the polygons for validity using GDAL isValid() when reading?

**Comment by hugoledoux** [comment]
We should, but then what do we do with them? Discard them? Warn user?

**Comment by tcommandeur** [comment]
A error it thrown in the current version.

if (!geometry->IsValid()) {
   std::cerr << "Geometry invalid: " << f->GetFieldAsString(idfield) << std::endl;
}

**Comment by tcommandeur** [comment]
The invalid geometries occurred due to broken shapefiles, code throws an error to notify.

About converting arcs to line segments, this is not as easy as stated. to be able to discretise lines topologically correct a robust arc-reversible algorithm needs to be used like GDAL which is not that easy to influence.
