### ISSUE TITLE
Missing attributes and geometry in IMGeo GML

### ISSUE THREAD

**Issue by grivy** [tudelft3d/3dfier#26]
Hi,
Looking at the first and last cityobjectmember in: https://3d.bk.tudelft.nl/download/3dfier/Delft.imgeo.zip
I noticed several attributes missing that have not been transferred from the BGT:
- The 2D geometries:
<imgeo:geometrie2dOverbruggingsdeel>
<imgeo:geometrie2dWaterdeel>

- Objectbegintijd an attribute every class has:
<cit:creationDate>2017-02-01</cit:creationDate>

- Class specific attributes (in both cases the 'Type' attribute (not the plustype and not the hoortbytype))
<bri:function codeSpace="http://www.geostandaarden.nl/imgeo/def/2.1#TypeOverbruggingsdeel">dek</bri:function>
<wat:class codeSpace="http://www.geostandaarden.nl/imgeo/def/2.1#TypeWater">waterloop</wat:class>

Note that I only looked at two objects, so more attributes from other IMGeo classes are likely to be missing too.

**Comment by tcommandeur** [comment]
This data is made with an old-old version and handling of input attributes is improve a lot.
