### ISSUE TITLE
Installation step for step

### ISSUE THREAD

**Issue by Abelon38** [tudelft3d/3dfier#28]
Hi! 
Thanks for this free solution! 
I would appreciate a lot som help with the installation! I am trying to install 3dfiler on Windows 10, 64bit and I dont know how to continue from here:

- Compile your own copies of Yaml-cpp and CGAL   (How to compile these??
- Set the path to the include folders in Project->C/C++->General->Additional Include Directories (Where to set the path? on Windows enviroment?)
- Set the path to the boost binaries in Project->Linker->General->Additional Library Directories (Where to set the path? on Windows enviroment?)
- Set the path to other libraries in Project->Linker->Input->Additional Dependencies (Where to set the path? on Windows enviroment?)
- Build solution (with Make i guess?)
Thank you for your time!
Abel

**Comment by Ylannl** [comment]
You can just directly download the [pre-compiled binaries](https://github.com/tudelft3d/3dfier/releases).

**Comment by Abelon38** [comment]
Hi Ylannl!

Thanks for your reply! I downloaded and run the 3dfier.exe in it. I guess this is a compile of Yaml-cpp and CGAL. 
About the: "Set the path to the include folders in Project->" Is the path on Windows Environment or wher should I set the paths?

Regards,
Abel

**Comment by tcommandeur** [comment]
Hi Abel,

You can either use the list you posted from the ReadMe or use the precompiled binaries as pointed out above. If you download the binaries everything you need is included. Just extract the zip file into a folder, open a console window and run 3dfier.exe.

Regards,
Tom
