### ISSUE TITLE
extrusion of 2 adjacent buildings to almost same height can cause self-intersections

### ISSUE THREAD

**Issue by hugoledoux** [tudelft3d/3dfier#29]
see that file, with 2 intersecting faces, as reported by Meshlab

[out.off.txt](https://github.com/tudelft3d/3dfier/files/976536/out.off.txt)

If one vertex is moved just a bit, then the problems vanishes. But there are still 3cm between the vertices. 

easy-fix: always snap roof heights to closest 10cm?

**Comment by tcommandeur** [comment]
This should be retested with v1.0

**Comment by tcommandeur** [comment]
out-of-date
