### ISSUE TITLE
invalid OBJ/GML output?

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/3dfier#30]
The OBJ/GML output might still has some issues in v0.96 (as also described in #20 ). It appears that the included example files (testarea.obj/gml) are already invalid and I cannot open them in FME or Blender due to parsing errors, also [val3dity](http://geovalidation.bk.tudelft.nl/) confirms the invalidity: 102, 104, 301, 302 (in case of testarea.obj). The output that I generate from the example data sets are also invalid with the same errors.

Meshlab can open the OBJ without problems.

I'm running Ubuntu 16.04, GDAL 2.1.0, liblas 1.8.1, laszip 2.2.0, yaml-cpp 0.5

**Comment by tcommandeur** [comment]
Thank you for noticing this, it seems we have not been updating the testarea obj and gml files since November. The current files in the master branch are created with v0.9.7.
