### ISSUE TITLE
Installation problem on Ubuntu: LibLAS library can't be found

### ISSUE THREAD

**Issue by ipasic** [tudelft3d/3dfier#33]
Hi,

I follow instructions for compiling on Linux but I can't make it work on my Ubuntu 14.04 because whenever I try to execute `cmake ..` command it complains about LibLAS library not being found even though it is already installed on the same system (i used that library already before and it works fine). All the other dependencies were found normally, it's only liblas that makes the problem.

I even tried to install again all dependencies (including libLAS) on new fresh Ubuntu 16.04 virtual machine (with no previous installations) but still, after i install all required dependencies and then try to build 3dfier it still complains about the same library.

Do you maybe know why is that, I was following [this documentation](https://www.liblas.org/compilation.html#using-unix-makefiles-on-linux) to install the libLAS, everything looked fine with that.

**Comment by hugoledoux** [comment]
Does that help?

**Comment by balazsdukai** [comment]
The link to the [build script](https://github.com/tudelft3d/3dfier/blob/build_ubuntu_2/ressources/build_ubuntu1604.sh) in the Wiki was incorrect. If you've downloaded it already, please do it again.

**Comment by ipasic** [comment]
Hi, thank you for your fast reply, I downloaded updated version of build script and tried to execute it on my Ubuntu 16.04 as described in Wiki but execution of the script failed at one moment with this error

`CMakeFiles/3dfier.dir/build.make:110: recipe for target 'CMakeFiles/3dfier.dir/Map3d.cpp.o' failed`

I tried the same procedure on another machine with Ubuntu 14.04 (just to check) but at one moment it also failed with error like this
`make[2]: *** [CMakeFiles/3dfier.dir/Map3d.cpp.o] Error 1`

I don't know is it of any help to you? Maybe you have idea why that happens?

Thanks, Ivan

**Comment by tcommandeur** [comment]
solved by scripts in #39
