### ISSUE TITLE
3dfier has stopped working on windows 10

### ISSUE THREAD

**Issue by jeanbarr** [tudelft3d/3dfier#34]
Hello
3dfier has stopped under windows 10.
When the application is launched, a message appears with the reading of the configuration file:
input_polygons:

  - datasets: 
      - k:/3dfier-windows-x64-v0.9.7/data/brindas_3946_b.shp
    uniqueid: osm_id
    lifting: Building  

input_elevation:
  - datasets:
      # - /Users/elvis/data/top10nl/schie/ahn2_u.laz
      # - /Users/elvis/data/top10nl/schie/ahn2_g.laz
      # - k:\3dfier-windows-x64-v0.9.7\data\1832_5170.laz
	- k:/3dfier-windows-x64-v0.9.7/data/1830_5171.laz
	#- k:\3dfier-windows-x64-v0.9.7\data/1831_5169.laz
	#- k:\3dfier-windows-x64-v0.9.7\data/1831_5170.laz
	#- k:\3dfier-windows-x64-v0.9.7\data/1832_5169.laz
	#- k:\3dfier-windows-x64-v0.9.7\data/1832_5171.laz
	#- k:\3dfier-windows-x64-v0.9.7\data/1831_5171.laz

    omit_LAS_classes:
      - 1 # unclassified
    thinning: 1

lifting_options:
  Building:
    height_roof: percentile-95
    height_floor: percentile-10
    triangulate: true
  building_radius_vertex_elevation: 3.0
  radius_vertex_elevation: 1.0
  threshold_jump_edges: 0.25

output: 
  format: CityGML # OBJ-NoID, OBJ-BUILDINGS, CityGML, CSV-BUILDINGS or Shapefile
  building_floor: false
  vertical_exaggeration: 3

buildings:
  horizontal_floor: true
  triangulated: false

**Comment by tcommandeur** [comment]
Jeanbarr,

From your message I cannot see what is happening. There seems to be no data on the error and the rest is configuration. The only thing I can see now is that there are laz files in the configuration from the example config (- /Users/elvis/data/top10nl/schie/ahn2_u.laz). This might result in problems. If this is not the case can you elaborate more on what error message you get? (You can attach a screenshot of the console)

**Comment by jeanbarr** [comment]
hello
Thanks for the response.
After several tests, I realized that the problem came from the configuration file.
By repeating exactly the same and adapting it to my data the program worked correctly.
I wanted to know if improvements were planned in order to be able to take into account parameters to obtain more conformable roofs.

**Comment by tcommandeur** [comment]
Good to know you got it working after all.

As for the roofs, we are looking into going into LoD1+, meaning splitting the building based on height differences an extruding them. This way buildings will still have flat planes as roof shapes but a better representation of the height differences.
