### ISSUE TITLE
ERROR: Missing polygon data, cannot 3dfy the dataset, abording

### ISSUE THREAD

**Issue by antoinebio** [tudelft3d/3dfier#35]
Hello,
I was starting 3Dfier on a simple dataset. I only extracted buiding outlines from a photogrammetric stereoplotting and prepared a SHP (polygons).
![capture](https://user-images.githubusercontent.com/30265851/28323523-68958a30-6bd9-11e7-882f-ce81041cfaa7.JPG)

Then I changed "config.yml" to match that shp and LAZ file.
However I have an issue with the shp file, console returns the following message:
![capture2](https://user-images.githubusercontent.com/30265851/28323677-c80423a0-6bd9-11e7-9257-fbccfa618c39.JPG)

In order to make it clear I tested with 3dfier-master\example_data, namely ahn3 & BGT.
Still the same issue in the console
Do you have any idea of the cause of that issue ?

Thanks,

antoine

**Comment by tcommandeur** [comment]
Have you tried using the path "shp\luz-bati.shp"? 
Notice the backslash instead of the forward slash, Windows is picky when it comes to paths.

**Comment by antoinebio** [comment]
oh ! tricky... thanks Windows !
Thanks you.
Is there any default field in the shp I can set as uniqueid in yml file ?
![image](https://user-images.githubusercontent.com/30265851/28368393-7ba7c140-6c94-11e7-985e-02ac050b7adf.png)
My source shp doesn't have some many field recorded, only a basic id described as "id de l'entité" in QGIS
![image](https://user-images.githubusercontent.com/30265851/28368458-b441f98a-6c94-11e7-8b42-0106bfe39ed1.png)

**Comment by tcommandeur** [comment]
If you leave the field blank in the configuration it defaults to 'fid' which is always created by GDAL while reading a file.
