### ISSUE TITLE
Issues with extruding land, vegetation and water

### ISSUE THREAD

**Issue by Digital-Banana** [tudelft3d/3dfier#40]
I followed along with the tutorial and created the city center of Leiden. Afterwards I wanted to try to create my own project by creating a small part of the harbor of Rotterdam.

I grabbed the BGT data and the AHN3 files from the PDOK website. Specifically I took the area with the code '37az2' at the far west of the Rotterdam harbor -- this was the AHN3/LAZ data. The problem I run into with building my model is that I'm only getting the buildings extruded.

I added a picture of my result. As you can see, there are no roads, vegetation, land or water visible. This is a problem. I added a dark grey plane underneat the city/buildings to make it more visible to show the issue.

- Kenny

**Comment by balazsdukai** [comment]
@Digital-Banana hm where did you post the picture? It doesn't appear here in your post.

But based on your description, it could be that 3dfier didn't find the input polygons for the missing features. You can specify them in the config, see the [template with instructions](https://github.com/tudelft3d/3dfier/blob/master/myconfig_README.yml)

(Alternatively) In case you filtered the point cloud (just didn't mention it here), it might be that the vegetation etc classes were removed.

**Comment by Digital-Banana** [comment]
Looks like I forgot to add it. Here it is!

![extrude](https://user-images.githubusercontent.com/11884374/31215900-bb48680e-a9b1-11e7-8c1e-e77849473fb7.jpg)

@balazsdukai It could be 3dfier didn't find the input polygons. I used the GML extension for my BGT files, not SQLite. Could this cause an issue as well?

I didn't filter the point cloud either. I haven't heard about that until now.

**Comment by tcommandeur** [comment]
Can you post the output of 3dfier? 

When using the GML directly there are some issues. First, you should extract the correct GFS files (somewhere in the resources folder) in the same folder as the gml files. This is a mapping for the geometries in the GML files to be read correctly. 

Also the BGT contains curves which are not supported by 3dfier so they need to be discretised. This can be done using GDALs ogr2ogr. In the resources folders subfolder bgt_prepair, there are batch files for conversion of the bgt. 

Follow the readme.md in that folder:
When preparing the BGT GML files as input for 3dfier, the BGT_conversion.bat batch script can be used. 
The script requires GDAL >2.0 to perform the filtering and conversion.
OGR is used to only select polygonal geometries and stroke CurvePolygons, it also filters the history of objects by selecting those of which the 'eindregistratie' is not set.

Usage:
- Extract the BGT GML files in a folder
- Copy all GFS files from "BGT gfs files" into the same folder
- Make sure all GFS files are newer then the GML files (assure this by editing all GFS files, add/remove a character, save, restore character, save)
- Run BGT_conversion.bat (or the commands within if on Linux/Mac)
- Use generated sqlite files as input to 3dfier

**Comment by Digital-Banana** [comment]
Sure. Here's my output.obj:
[output.zip](https://github.com/tudelft3d/3dfier/files/1358577/output.zip)

I haven't done that gfs conversion -- I'm pretty certain it's the gml files that are causing the issue then. I will try the gfs conversion next and let you know what happens.

Do you think it could also be an issue of the BGT and AHN3 files? It's because I've downloaded _roughly_ the same areas from the PDOK website, but the grids there don't align which means not all data overlaps with each other. But it's probably just the gfs conversion I still need to do.

**Comment by Digital-Banana** [comment]
When I run the BGT_conversion.bat it opens the command prompt for a split second then shuts down again -- with no files changed or added. 

- I extracted the BGT GML files in a folder
- Put the GFS files in that same folder
- Made sure the GFS files are newer than the GML files
- Ran BGT_conversion.bat (I'm on Windows) and nothing happened.

I will try again with a different dataset, maybe the BGT data from that area is bugged? Also, the only way for me to get the GFS files is by dropping the BGT GML files into QGIS Desktop Version who then creates the GFS files.

**Comment by tcommandeur** [comment]
1. As for the data input: If you input bgt polygons and the AHN doesn't overlap there, it creates polyons at 0m height. As we can see from your image the tiles don't overlap completely but for some part (there where the buildings are >0m). You can allways add more AHN tiles in the config for the other regions as it will automatically discard points which are not overlapping the polygons.

2. As explained above, the GFS files are in this repository: https://github.com/tudelft3d/3dfier/tree/master/ressources/BGT_prepare/BGT_gfs_files 
These must be used instead of the automatically created ones from QGIS.

3. Install OSGeo4W https://trac.osgeo.org/osgeo4w/ to get the GDAL binaries and ogr2ogr. If you done this, open a command window and browse to the folder in which you placed the GML files and bgt_conversion.bat. Execute bgt_conversion.bat in this folder and the output will multiple .gpkg files. Use these files as input for 3dfier instead of the GML files.

4. If you run into more issues please send a zip containing the following:
All .gpkg files
All .laz filenames (not the files themselves, they are to big)
3dfier configuration YAML file
Screenshot of the console output of 3dfier.exe

**Comment by Digital-Banana** [comment]
I installed OSGeo4W. When I run bgt_conversion.bat I get the following error message: 'ogr2ogr' is not recognized as an internal or external command, operable program or batch file.

I'm making progress, but how do I install ogr2ogr?

**Comment by Digital-Banana** [comment]
I fixed ogr2ogr. I run into the same issues however. I added a . zip of all .gpkg files, .laz filenames, yaml config and screenshots of the console output after I run it. It shows several errors.

[digitalbanana_3drdam.zip](https://github.com/tudelft3d/3dfier/files/1359560/digitalbanana_3drdam.zip)

**Comment by tcommandeur** [comment]
Do you have a file called bgt_tunneldeel.gml? I guess not, you can remove this ogr2ogr line by opening the bat file using notepad. If the file is there it could be that it contains no geometries so you should remove it anyhow.

**Comment by tcommandeur** [comment]
Did you get this resolved?

**Comment by Digital-Banana** [comment]
@tcommandeur Hey. Not yet, I will try again somewhere this week. You can close this if you want -- if I run into problems I will open another topic.
