### ISSUE TITLE
ERROR: field 'hoogtenive' not found in layer *, using all polygons.

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/3dfier#45]
On `master`.
The error about the missing 'hoogtenive' appears for each input layer, but it doesn't seem to affect the output. But neither did I specify anything related to 'hoogtenive' in the config. Is this sth to worry about?

**Comment by tcommandeur** [comment]
The height_field is only used if a data set has overlapping structures like bridges, if not you can use all polygons for reconstruction which is the default fallback if the attribute is not found. 

I changed the text from ERROR to Warning to make it look less harmfull as well as change hoogtenive default to heightfield to make the error more understandable for non Dutch.
