### ISSUE TITLE
Minimum nr. of points for triangulation

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/3dfier#47]
On `master`.
I have a point cloud where I separated the *ground* (2) points from the rest and filtered them. When I run 3dfier with the filtered ground points, the terrain is not generated/triangulated and it seems that the input polygons for the road (grey), terrain (yellow) features are ignored. However, the 'Auxilliary Traffic Area' (purple) polygons do receive points and get triangulated. Is there a minimum of the required points for the triangulation?

I'm using `thinning: 0` for the point cloud and `simplification: 0` for the terrain. 
I'm using BGT polygons and prepared them according to the instructions.

3dfy with unfiltered point cloud:
![full](https://user-images.githubusercontent.com/7190603/32052655-42cad480-ba59-11e7-9438-512c9bf5cb4c.png)

The filtered point cloud (only the ground points are filtered):
![pc](https://user-images.githubusercontent.com/7190603/32052693-5d409b92-ba59-11e7-88de-f772bc5af0b5.png)

3dfy with the same settings as above, but with the filtered pc:
![simplified](https://user-images.githubusercontent.com/7190603/32052732-6efa9090-ba59-11e7-8ee6-8dfdc4c7c60a.png)

Input and config files:
https://www.dropbox.com/s/hiwazpyj0k30kbe/simplified.zip?dl=0

**Comment by tcommandeur** [comment]
Looking at the results I guess you forgot to classify the 206000_376500_ground_simplified.laz points as ground. Seperation uses `lasclass != LAS_BUILDING && lasclass != LAS_WATER` so it does get points added classified as non ground. The Road and Terrain classes use `lasclass == LAS_GROUND` thus only points classified as ground are added.

**Comment by tcommandeur** [comment]
I quickly classified 206000_376500_ground_simplified.laz using `las2las -set_classification 2 -olaz` and the results looks a lot better now.

![snapshot01](https://user-images.githubusercontent.com/19147421/32112437-96a312c2-bb3d-11e7-81ca-4ac6486eb39b.png)

**Comment by balazsdukai** [comment]
Yep, just did the same :-), good catch!
