### ISSUE TITLE
ONLY BUILDING...

### ISSUE THREAD

**Issue by antoinebio** [tudelft3d/3dfier#48]
HELLO,
When I run 3D fier on 2 classified pointcloud + shp 3DFIER returns only building in 3D...without DTM triangulation (?)
see below my LAZ input :
![capture](https://user-images.githubusercontent.com/30265851/32054849-1d856792-ba60-11e7-89a8-41baa2b34d20.JPG)

and see the result in meshlab :
![capture1](https://user-images.githubusercontent.com/30265851/32054894-56246f4e-ba60-11e7-8e46-c2a9b9e9b107.JPG)
My source shp is well extruded, but terrain is missing...

any idea why ?
thanks
antoine

**Comment by tcommandeur** [comment]
Do you have shapefile describing your terrain? 3dfier only creates 3D objects of the shapefile inputs. What you can do is create a shapefile with the extent of you point cloud,remove the buildings from it and configure that shapefile as a terrain layer.

This is related to #14, I will make a description in the readme soon.

**Comment by antoinebio** [comment]
it makes 3D fier crashes right after running the command.
attached are my 2 shp. One for building, one for terrain boudaries.
[shp.zip](https://github.com/tudelft3d/3dfier/files/1426752/shp.zip)
also the config file below
[config.zip](https://github.com/tudelft3d/3dfier/files/1426755/config.zip)

**Comment by tcommandeur** [comment]
First of all you configured 'uniqueid' of the buildings to the 'area' attribute which is not a unique value. Please create an attribute which has a unique value for each feature and use that.

As for why it crashes, I have no idea. Is there any console output at all? If not the issue is in the configuration most of the times, however from looking at it I cannot see the problem right away (except for the uniqueid described before). Can you try again by using a correct uniqueid and if it still fails send the laz files so I can debug the code?

**Comment by antoinebio** [comment]
I don't think that  __'uniqueid' of the buildings_ is an issue. In my config file If I remove the dataset for terrain 3Dfier works without any issue and returns 3D buildings (see https://user-images.githubusercontent.com/30265851/32054894-56246f4e-ba60-11e7-8e46-c2a9b9e9b107.JPG)
However I can try to change that, create an attribute with an unique value.
As for the command I can only say 3Dfier returns a windows crash
![image](https://user-images.githubusercontent.com/30265851/32166596-a1684184-bd66-11e7-8c3c-67dfde568494.png)

**Comment by tcommandeur** [comment]
Good point about the uniqueid, its indeed not forced in the code to be unique. 

Can you send me the laz files so I can debug the issue?

**Comment by antoinebio** [comment]
here it is

https://mega.nz/#F!ItpnUIJL!0zkGxx2bsODR-rRAwBYc_A

I also send you the lasinfo summary
[lasinfo-laz.zip](https://github.com/tudelft3d/3dfier/files/1426935/lasinfo-laz.zip)

**Comment by tcommandeur** [comment]
Debugging crashed when the YAML file was read, it turns out the config file is not valid. There are no whitespaces in front of the second `- datasets;`  You can validate the format of the config file using www.yamllint.com, I will add this to the ReadMe. Also I will add an error message for invalid YAML files.

**Comment by tcommandeur** [comment]
Also for the best result you should clip the buildings from the terrain so features of both shapefile do not intersect (all shapefiles combines should be a planar partition). Now the terrain is not stitched to the buildings as you can see in the image below. 

![snapshot01](https://user-images.githubusercontent.com/19147421/32173650-fea27018-bd7f-11e7-9124-a7d6e91956ab.png)

**Comment by antoinebio** [comment]
thanks !

**Comment by antoinebio** [comment]
when you say "clip the buildings from the terrain" I guess you mean adding the option   stitching: true ...?
I tried, but it changes nothing...
Did I misunderstood something in order to set it ?

**Comment by tcommandeur** [comment]
I mean to adjust the terrain polygon by removing the buildings from it. You can use symmetrical difference in QGIS to do so.
See http://grindgis.com/software/qgis/basic-editing-tools-in-qgis -> D. Symmetrical Difference. This is needed so the terrain and building polgyons do not intersect but only touch.

**Comment by antoinebio** [comment]
I see, Holes in terrain shp at building location. Boolean operator between building shp and terrain shp should give what is required.
Thanks.
Antoine

Envoyé de mon GSM / sent from my GSM

**Comment by antoinebio** [comment]
Symmetrical diff has been done.
however When running 3Dfier I've got a crash
see below
![image](https://user-images.githubusercontent.com/30265851/32214817-62a6b9e8-be20-11e7-98b2-6715a06bbf0f.png)

**Comment by antoinebio** [comment]
ok issue was due to wrong attribute copied by Symmetrical Difference operation. Everything works fine.

**Comment by tcommandeur** [comment]
Nice to hear you got it to work. Can you maybe share some images of the results? If its okay with you I would like to update the wiki page on this issue using these. For that I would require some images on the 2D terrain polygons, the 2D terrain + buildings and some 3D results, also where the buildings are stitched into the terrain.

**Comment by antoinebio** [comment]
terrain
![image](https://user-images.githubusercontent.com/30265851/32222599-30d38b70-be3a-11e7-90ad-000218305924.png)

Symmetrical Difference operation result
![image](https://user-images.githubusercontent.com/30265851/32222645-62cf1964-be3a-11e7-9a70-746222d0c53a.png)

2D terrain + buildings
![image](https://user-images.githubusercontent.com/30265851/32222677-7acc1a3a-be3a-11e7-8737-c0637005a6ba.png)

3D result on OBJ in Meshlab
![image](https://user-images.githubusercontent.com/30265851/32222728-b87a5112-be3a-11e7-892e-32e4afee01ca.png)

viewpoint below the 3d model
![image](https://user-images.githubusercontent.com/30265851/32222770-e95b2a40-be3a-11e7-88c2-c026412ebc9e.png)

also viewpoint below the GML output display in[ FZK viewer](https://www.iai.kit.edu/1302.php)
![image](https://user-images.githubusercontent.com/30265851/32222837-1b471938-be3b-11e7-8abf-9eea8048581c.png)

**Comment by antoinebio** [comment]
I share my input dataset & result here for you

https://mega.nz/#F!ItpnUIJL!0zkGxx2bsODR-rRAwBYc_A

**Comment by antoinebio** [comment]
I tried to add river boundaries in the final GML.
water has been classfied in the source laz
river boundaries are also input in an extra shp
below is what I've got
I don't understand why the the water is a independent polygon below the terrain. shouldn't it be stitched to the terrain ?
![image](https://user-images.githubusercontent.com/30265851/32229413-0a019d9a-be51-11e7-8406-5b358c65356a.png)
