### ISSUE TITLE
Improve YAML validation

### ISSUE THREAD

**Issue by Ylannl** [tudelft3d/3dfier#52]
While most of the YAML file is validated before the processing is performed, if one omits the `building_floor` attribute in the YAML file, 3dfier will still crash before it has written the output. Potentially after hours of processing 😐.

I am guessing this [line](https://github.com/tudelft3d/3dfier/blob/feaaacee05a88371ecec398a101d702c945af081/main.cpp#L373) is the culprit (ie. trying to convert a non existing element to string).

**Comment by tcommandeur** [comment]
This has been fixed. More of the same have been found and fixed.
