### ISSUE TITLE
many-outputs: files can't be created

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/3dfier#63]
On `feature/many-outputs` branch:
```
$ 3dfier 25gn_many-outputs.yml --CSV-BUILDINGS /many-outputs/25gn.csv
```
Returns:
```
ERROR: file /many-outputs/25gn.csv can't be created. Abort
```
Although I have the necessary permissions on the directory.

**Comment by hugoledoux** [comment]
fixed in 7e3d46e498cd886ea25aa87ea7da39a4e4b16433 (well works for me both on macOS and Linux)
