### ISSUE TITLE
ERROR IN CPNFIGURING CGAL. build files for visual studio 2017 not creating.

### ISSUE THREAD

**Issue by PURNIMA1298** [tudelft3d/3dfier#69]
when i entered the command for build files for visual basic i am getting the folllowing error-D:\CGAL-4.12>cmake . -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=OFF -DBoost_USE_STATIC_LIBS=ON
-- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.16299.
== Setting paths ==
-- Build CGAL from release in directory CGAL-4.12
-- Packagenames: CGAL-4.12
== Setting paths (DONE) ==

== Generate version files ==
-- CGAL_MAJOR_VERSION=4
-- CGAL_MINOR_VERSION=12
-- CGAL_BUGFIX_VERSION=0
-- CGAL_SONAME_VERSION=13
-- CGAL_SOVERSION     =13.0.2
-- CGAL_REFERENCE_CACHE_DIR=
-- Building static libraries
-- Visual Leak Detector (VLD) is not found.
-- Targetting Visual Studio 15 2017 Win64
-- Target build enviroment supports auto-linking
-- Using VC14 compiler.
-- Generator uses intermediate configuration directory: $(Configuration)
-- USING CMake version: 3.11.2
-- System: Windows
== Generate version files (DONE) ==

-- Multi-configuration CMake generator: cannot display flags
== Detect external libraries ==
-- External libraries supported: GMP;MPFR;ZLIB;OpenGL;LEDA;MPFI;RS;RS3;OpenNL;Eigen3;BLAS;LAPACK;QGLViewer;ESBTL;Coin3D;NTL;IPE
-- Preconfiguring library: GMP ...
-- GMP has been preconfigured:
--   UseGMP-file:
--   GMP include:      D:/CGAL-4.12/auxiliary/gmp/include
--   GMP libraries:    D:/CGAL-4.12/auxiliary/gmp/lib/libgmp-10.lib
--   GMP definitions:
-- USING GMP_VERSION = '5.0.1'
-- Preconfiguring library: MPFR ...
-- MPFR has been preconfigured:
--   UseMPFR-file:
--   MPFR include:      D:/CGAL-4.12/auxiliary/gmp/include
--   MPFR libraries:    D:/CGAL-4.12/auxiliary/gmp/lib/libmpfr-4.lib
--   MPFR definitions:
-- USING MPFR_VERSION = '3.0.0'
CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:2044 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  cmake/modules/CGAL_SetupBoost.cmake:50 (find_package)
  cmake/modules/CGAL_SetupDependencies.cmake:85 (include)
  CMakeLists.txt:674 (include)

-- Boost include dirs: Boost_INCLUDE_DIR-NOTFOUND
-- Boost libraries:
== Detect external libraries (DONE) ==

== Write compiler_config.h ==
-- Performing Test CGAL_CFG_DENORMALS_COMPILE_BUG - Success
-- Performing Test CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG - Failed
-- Performing Test CGAL_CFG_IEEE_754_BUG - Success
-- Performing Test CGAL_CFG_ISTREAM_INT_BUG - Success
-- Performing Test CGAL_CFG_MATCHING_BUG_5 - Success
-- Performing Test CGAL_CFG_MATCHING_BUG_6 - Failed
-- Performing Test CGAL_CFG_MATCHING_BUG_7 - Success
-- Performing Test CGAL_CFG_MATCHING_BUG_8 - Success
-- Performing Test CGAL_CFG_NO_LIMITS - Success
-- Performing Test CGAL_CFG_NO_NEXTAFTER - Success
-- Performing Test CGAL_CFG_NO_STL - Success
-- Performing Test CGAL_CFG_NUMERIC_LIMITS_BUG - Success
-- Performing Test CGAL_CFG_OUTOFLINE_MEMBER_DEFINITION_BUG - Success
-- Performing Test CGAL_CFG_TEMPLATE_IN_DEFAULT_PARAMETER_BUG - Success
-- Performing Test CGAL_CFG_TYPENAME_BEFORE_DEFAULT_ARGUMENT_BUG - Success
-- Performing Test CGAL_CFG_USING_BASE_MEMBER_BUG_2 - Success
== Write compiler_config.h (DONE) ==

== Generating build files ==
Configuring libCGAL
CMake Error at cmake/modules/CGAL_SetupBoost.cmake:89 (message):
  use_CGAL_Boost_support is use whereas Boost_FOUND is false.
Call Stack (most recent call first):
  cmake/modules/CGAL_SetupCGALDependencies.cmake:104 (use_CGAL_Boost_support)
  src/CGAL/CMakeLists.txt:11 (CGAL_setup_CGAL_dependencies)

-- Configuring incomplete, errors occurred!
See also "D:/CGAL-4.12/CMakeFiles/CMakeOutput.log".
See also "D:/CGAL-4.12/CMakeFiles/CMakeError.log"

what to do now?

**Comment by tcommandeur** [comment]
The problem is within the message you post:
Unable to find the Boost header files. Please set BOOST_ROOT to the root
directory containing Boost or BOOST_INCLUDEDIR to the directory containing
Boost's headers.

For building CGAL you also need boost and setup the BOOST_ROOT path in your environment settings.
