### ISSUE TITLE
error in compliling 3dfier 

### ISSUE THREAD

**Issue by PURNIMA1298** [tudelft3d/3dfier#70]
i have downloaded 3dfier-master.zip and i downloaded visual stuudio projects mentioned and over writed the files in vs_build . when i open 3dfier.sln  and build the solution . i get this error

Error	MSB8036	The Windows SDK version 10.0.16299.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".	3dfier	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\PlatformToolsets\v141\Toolset.targets	36	
now what to do

**Comment by tcommandeur** [comment]
If you want to run 3dfier please just download one of the zip files from the release page https://github.com/tudelft3d/3dfier/releases. If you want to build 3dfier from source you should follow the clear explanation in the error message:
Change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".

Also If you have additional questions, could you please post them in this same issue instead of opening a new one?

Kind regards

**Comment by PURNIMA1298** [comment]
thanks for the answer . Actually i am quite new to 3dfier . If i need to
use my own dataset to create city gml do we need to build from source or
run the application alone? Also the application is crashing in my windows
Any help fr these questions



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/24/18,
5:56:48 PM

**Comment by tcommandeur** [comment]
If you want to just run 3dfier with your own data you should download the binaries from the releases page as noted before. For running 3dfier please refer to the Wiki document: [Running the precompiled 3dfier binary on Windows 64 bit 7, 8 or 10](https://github.com/tudelft3d/3dfier/wiki/Running-the-precompiled-3dfier-binary-on-Windows-64-bit-7,-8-or-10)

Also please first read the wiki [General 3dfier tutorial to generate LOD1 models](https://github.com/tudelft3d/3dfier/wiki/General-3dfier-tutorial-to-generate-LOD1-models) to understand what 3dfier does and how it works.

**Comment by PURNIMA1298** [comment]
i m getting an error in creating output-

D:\3dfier-master>3dfier.exe
ERROR: one YAML config file must be specified.

Allowed options:
  --help                        View all options
  --version                     View version
  --license                     View license
  --OBJ arg                     Output
  --OBJ-NoID arg                Output
  --CityGML arg                 Output
  --CityGML-Multifile arg       Output
  --CityGML-IMGeo arg           Output
  --CityGML-IMGeo-Multifile arg Output
  --CityJSON arg                Output
  --CSV-BUILDINGS arg           Output
  --CSV-BUILDINGS-MULTIPLE arg  Output
  --CSV-BUILDINGS-ALL-Z arg     Output
  --Shapefile arg               Output
  --Shapefile-Multifile arg     Output
  --PostGIS arg                 Output
  --PostGIS-Multi arg           Output
  --PostGIS-PDOK arg            Output
  --GDAL arg                    Output


D:\3dfier-master>$ ../build/3dfier testarea_config.yml -o
output/myoutput.obj
'$' is not recognized as an internal or external command,
operable program or batch file.
what to do now?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/25/18,
10:32:09 AM

**Comment by tcommandeur** [comment]
Please refer to this tutorial on how to run a program from the command line: https://www.wikihow.com/Run-a-Program-on-Command-Prompt

I cannot lead you through every single step of how to run 3dfier. You need to at least have basic knowledge on how to run a program. If you don't now what the location is of your executable, don't know how to run it I cannot help. Please find anybody who has the basic knowledge of these things to get you started.
