### ISSUE TITLE
Import of LandUse terrain components into 3DCityDB

### ISSUE THREAD

**Issue by christianbraun** [tudelft3d/3dfier#74]
Dear all,
how can I import relief or terrain components as surface or TIN into 3DCityDB?
I have generated a terrain layer in 3Dfier. In the output GML they are tagged as LandUse and are imported into 3DCityDB like that but the geometries are empty or not properly registered (what I got so far).
Which steps are necessary to get a surface representation in 3DCityDB which I can use with ST_3DIntersects?

Many thanks in advance,
Christian

**Comment by tcommandeur** [comment]
Hi Christian,

As far as we know the CityGML generated by 3dfier is valid. You could check the validity of the generated file by using [Val3dity](http://geovalidation.bk.tudelft.nl/val3dity/). If the file is valid then please refer to the developers of 3DCityDB on why the import is not working as expected.
