### ISSUE TITLE
not compiling on linux

### ISSUE THREAD

**Issue by najtin** [tudelft3d/3dfier#83]
doesnt build on its own because of missing dependencies 

no further hint for installation on linux except for

> For Linux we suggest taking a look at the travis build scripts for Ubuntu.

We would love to have some more information on how to build it on a regular pc using any linux system.

**Comment by evetion** [comment]
The dependencies are stated in that same section,

```
1   LIBLAS with LASzip support
2   GDAL
3   Boost
4   CGAL
5   yaml-cpp
```

If you look in the `.travis.yml` file (or the appveyor one), you see that we install 2, 3 and 5 from the ubuntu repositories themselves. We install 1 by using `resources/build_ubuntu/build_deps.sh`, 4 using `resources/build_ubuntu/build_cgal.sh` and finally we build 3dfier itself with `resources/build_ubuntu/build_3dfier.sh`

For distributions other than Ubuntu, you should be able to find 2, 3 and 5 in your package repositories. The other steps build from source and should work on most linux systems.
