### ISSUE TITLE
Output always in RD New

### ISSUE THREAD

**Issue by ImkeLansky** [tudelft3d/3dfier#86]
Hi, when I run 3dfier with for example the CityGML output, and then open the file in for example QGIS or look at it in a text editor, the CRS is always EPSG 7415. However, my input data does not contain this CRS at all. I cannot find any option to change the output CRS myself. I don't know what is causing this behaviour.

**Comment by tcommandeur** [comment]
Hi Imke,

The export EPSG to CityGML is hardcoded to 7415. This is only the number in the header of the file which you can change manually. The coordinates are the same as the input.

Cheers,
Tom
