### ISSUE TITLE
Using GeoTIFF data

### ISSUE THREAD

**Issue by PuzzlePJ** [tudelft3d/3dfier#87]
I want to use 3dfier on buildings in Austria. Unfortunately, Ihe regional governments do not publish the original LIDAR data but only digital surface and terrain models (DSM and DTM files) as GeoTIFFs. Is it possible to use these files directly with 3dfier or do you know a way to create as LAS file from them?

**Comment by tcommandeur** [comment]
GeoTIFF files cannot be read by 3dfier directly. You should convert them to LAS first. Multiple solutions should be there for the conversion, start by taking a look at lastools, pdal or similar tools.
