### ISSUE TITLE
Relative z values in gml - Floating buildings in Cesium

### ISSUE THREAD

**Issue by baffioso** [tudelft3d/3dfier#97]
I am using 3dfier to generate CityGML for Cesium Ion but are getting floating buildings.
![image](https://user-images.githubusercontent.com/7534153/69896381-2900b100-133f-11ea-944a-0f3e142d9f0d.png)
This is due to absolute z-value for building elements. I'm able to clamp the building to the ground if I change z-values of the different elements ( e.g. `<bui:lod0FootPrint>`)  to relative values (z-value of all building footprints is set to 0). 

Is it possible to configure 3dfier to create buidings with realtive z values where the footprint is 0 and the roof is the height of the buildig?

**Comment by tcommandeur** [comment]
There is no setting in 3dfier to switch from absolute heights to relative heights. The reason for this is that when combining the buildings  with other objects there will be a gap between them.

You could write a simple script that takes all z-values of a building and seperate the roof and floor value, then replace the roof value with (roof-floor) and the floor value with 0. If you don't subtract the floor value from the roof the building will not have the correct height.

**Comment by baffioso** [comment]
Will look into that solution. Thanks for the tool!!
